### ISSUE TITLE
Request: Dim/Disable/Grey GUI Min/Max Force when no effect for selected FFB Type

### ISSUE THREAD

**Issue by samkatakouzinosracing** [nlp80/irFFB#1]
I believe ability to change sliders for all FFB Type may mislead users in thinking they have an effect. 
When an FFB Type is selected that is affected by iRacing only then dim/disable/grey the relevant sliders so they cannot be changed.

**Comment by nlp80** [comment]
We couldn't do this whilst we still had the testing functionality in place as the FFB type that was being compared might have needed the sliders even if the primary type did not, and vice versa. I'm soon to commit changes that remove the testing functionality and will implement this at the same time..

**Comment by nlp80** [comment]
Fixed as far as possible in 54c288f..
