### ISSUE TITLE
Vjoy is not working with new Windows 10 update 1803.

### ISSUE THREAD

**Issue by X4rLy** [nlp80/irFFB#11]
Hi,

Since the last update of Windows 10 (1803) Vjoy is not working for some people, i had a conversation with the developer (Shaul) and he don't know what is the problem, and the development of vjoy is finished, then the people with this issue can't use irffb.

Is any program like Vjoy that we can use with irffb?

Thanks in advance.

**Comment by imagebuff** [comment]
Any updates on this issue?  If this issue is correct it effectively kills irFFB.  Any way to address this showstopper issue with higher priority?

Thanks !!

**Comment by nlp80** [comment]
Shaul released a new version of vJoy that addresses this problem: https://github.com/shauleiz/vJoy/releases
