### ISSUE TITLE
Request: Have slider values show in the app

### ISSUE THREAD

**Issue by samkatakouzinosracing** [nlp80/irFFB#5]
I request slider values to display as text in the app. 

Currently the slider values are not readable/visible within the app. 
Except for when you click on the slider 'notch'. 

One suggestion is to display the value as text after the sliders labels colon ':' .

Examples;

Min force: 0 
0 |-------- 20 

Max force: 27 Nm 
5 Nm ---|----- 65 Nm
 
Suspension bumps: 44
0 ----|---- 100

Suspension load: 77
0 ------|-- 100

Implementing this request would support; 
- easier reading of the values that are being used without having to touch the slider. 
- allow screen shots of the app to share with others with values shown.

**Comment by nlp80** [comment]
Implemented in 01650fa
