### ISSUE TITLE
No FFB on direct mode for some cars

### ISSUE THREAD

**Issue by fuzunspm** [nlp80/irFFB#8]
I don't know if i'm missing something here but on direct modes i loose all of the ffb for some cars like ferrari gt3 or silverado but works on porsche. 

Directo filtered 720
DFGT

**Comment by nlp80** [comment]
Sounds like you need to recalibrate iRacing's steering for the cars for which you have no FFB. It helps if you uncheck iRacing's car specific settings checkbox for all cars; that way every car should use the same calibration.

**Comment by fuzunspm** [comment]
That did the trick, thank you very much
